### ISSUE TITLE
ValueError: Unable to process empty list

### ISSUE THREAD

**Issue by kenorb** [yodiaditya/slideshare-downloader#6]
```
$ pip3 install -r requirements_py3.txt
...
Successfully installed beautifulsoup4-4.10.0 bs4-0.0.1 img2pdf-0.4.3 lxml-4.8.0 pikepdf-5.0.0 soupsieve-2.3.1

$ python3 convertpdf.py https://www.slideshare.net/gskachkov/webassembly-vs-javascript-what-is-faster
yodiaditya/slideshare-downloader/convertpdf.py:22: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 22 of the file yodiaditya/slideshare-downloader/convertpdf.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(html)
[]
Traceback (most recent call last):
  File "yodiaditya/slideshare-downloader/convertpdf.py", line 75, in <module>
    download_images(url)
  File "yodiaditya/slideshare-downloader/convertpdf.py", line 31, in download_images
    convert_pdf(title)
  File "yodiaditya/slideshare-downloader/convertpdf.py", line 55, in convert_pdf
    pdf_bytes = img2pdf.convert(f, dpi=300, x=None, y=None)
  File "~/.local/lib/python3.9/site-packages/img2pdf.py", line 2223, in convert
    raise ValueError("Unable to process empty list")
ValueError: Unable to process empty list
```

**Comment by zhiyelee** [comment]
<img width="2108" alt="image" src="https://github.com/yodiaditya/slideshare-downloader/assets/681150/f8b1598a-d75f-4cb5-85dd-8165f726e39a">

I think they have updated the html structure, applying this diff will fix the issue

**Comment by yodiaditya** [comment]
Bug fixed and upgraded with latest version work with Slideshare 2024 layout. Thank you @zhiyelee  @kenorb !

**Comment by yodiaditya** [comment]
Bug fixed and upgraded with latest version work with Slideshare 2024 layout. Thank you @zhiyelee  @kenorb !
