### ISSUE TITLE
Failed to run script 

### ISSUE THREAD

**Issue by kholis** [yodiaditya/slideshare-downloader#7]
Hi, I found these error when trying to execute your script

```
$ python slideshare2pdf.py https://www.slideshare.net/robertmetzger1/apache-flink-hands-on
Traceback (most recent call last):
  File "/home/opc/slideshare-downloader/slideshare2pdf.py", line 36, in <module>
    driver = webdriver.Chrome("/snap/bin/chromium.chromedriver", options=options)
TypeError: WebDriver.__init__() got multiple values for argument 'options'
```
Please kindly advise. Thank you

**Comment by kholis** [comment]
Hi, I edit script based on [https://stackoverflow.com/a/76432322/1377004](url)

then download chromedriver match with my env [here](https://googlechromelabs.github.io/chrome-for-testing/)

the script now run. but found this error:

```
Traceback (most recent call last):
  File "/Users/kholis/Projects/slideshare-downloader/slideshare2pdf.py", line 122, in <module>
    download_images(url)
  File "/Users/kholis/Projects/slideshare-downloader/slideshare2pdf.py", line 62, in download_images
    image_url = image.get('srcset').split('w, ')[-1].split(' ')[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by kholis** [comment]
Hi,

Fix the issue by changing `'srcset'` to `'data-srcset'`

Thanks for the script.
